adminUser:
  password: vault:testclusterrrrrrrr/adminUser:password
  username: admin
enableDocker: false
pipelineUser:
  email: ldonley+github@cloudbees.com
  token: vault:testclusterrrrrrrr/pipelineUser:token
  username: ld-bot
prow:
  hmacToken: vault:testclusterrrrrrrr/prow:hmacToken
